config/routes.rb
Rails.application.routes.draw do
  # resources :linebots
  # root 'linebots#index'
  resources :posts
  post '/callback' => 'linebot#callback'

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/linebot.rb
class Linebot < ApplicationRecord
end

app/models/post.rb
class Post < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/linebots_controller.rb
class LinebotsController < ApplicationController
  # before_action :set_linebot, only: %i[ show edit update destroy ]

require 'line/bot'

protect_from_forgery :except => [:callback]

def client
  @client ||=line::Bot::Client.new{|config|
  config.channel_secret = ENV["LINE_CHANNEL_SECRET"]
  config.cahnnel_token = ENV["LINE_CHANNEL_TOKEN"]
  }
end

def callback
  @post = post.offset(rand(Post.count)).first
  body = request.body.read
  
  signature = request.env['HTTP_X_LINE_SIGNATURE']
  unless cilent.validate_signature(body,signature)
    head :bad_request
end

events = client.parse_events_form(body)

events.each{ |event|

  if event.message['text'].include("テスト")
    response = "アンサー"
  elsif event.message["text"].include?("テストテスト")
    response = "アンサー2"
  elsif event.message['text'].include?("テストテストテスト")
    response = "アンサー3"
  elsif event.message['text'].include?("テストテストテストテスト")
    response = "アンサー4"
  else
    response = @post.name
  end

    case event
    when LINE::Bot::Event::Message
      case event.type
      when Line::Bot::Event::MessageType::Text
        message = {
          type: 'text',
          text: response
        }
        client.reply_message(event['replyToken'],message)
        end
      end
    }
    head :ok
  end
end


  # GET /linebots or /linebots.json
#   def index
#     @linebots = Linebot.all
#   end

#   # GET /linebots/1 or /linebots/1.json
#   def show
#   end

#   # GET /linebots/new
#   def new
#     @linebot = Linebot.new
#   end

#   # GET /linebots/1/edit
#   def edit
#   end

#   # POST /linebots or /linebots.json
#   def create
#     @linebot = Linebot.new(linebot_params)

#     respond_to do |format|
#       if @linebot.save
#         format.html { redirect_to @linebot, notice: "Linebot was successfully created." }
#         format.json { render :show, status: :created, location: @linebot }
#       else
#         format.html { render :new, status: :unprocessable_entity }
#         format.json { render json: @linebot.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # PATCH/PUT /linebots/1 or /linebots/1.json
#   def update
#     respond_to do |format|
#       if @linebot.update(linebot_params)
#         format.html { redirect_to @linebot, notice: "Linebot was successfully updated." }
#         format.json { render :show, status: :ok, location: @linebot }
#       else
#         format.html { render :edit, status: :unprocessable_entity }
#         format.json { render json: @linebot.errors, status: :unprocessable_entity }
#       end
#     end
#   end

#   # DELETE /linebots/1 or /linebots/1.json
#   def destroy
#     @linebot.destroy
#     respond_to do |format|
#       format.html { redirect_to linebots_url, notice: "Linebot was successfully destroyed." }
#       format.json { head :no_content }
#     end
#   end

#   private
#     # Use callbacks to share common setup or constraints between actions.
#     def set_linebot
#       @linebot = Linebot.find(params[:id])
#     end

#     # Only allow a list of trusted parameters through.
#     def linebot_params
#       params.require(:linebot).permit(:title, :body)
#     end
# end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/linebots_helper.rb
module LinebotsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LineBot</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/linebots/_form.html.erb
<%= form_with(model: linebot) do |form| %>
  <% if linebot.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(linebot.errors.count, "error") %> prohibited this linebot from being saved:</h2>

      <ul>
        <% linebot.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/linebots/edit.html.erb
<h1>Editing Linebot</h1>

<%= render 'form', linebot: @linebot %>

<%= link_to 'Show', @linebot %> |
<%= link_to 'Back', linebots_path %>

app/views/linebots/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Linebots</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Body</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @linebots.each do |linebot| %>
      <tr>
        <td><%= linebot.title %></td>
        <td><%= linebot.body %></td>
        <td><%= link_to 'Show', linebot %></td>
        <td><%= link_to 'Edit', edit_linebot_path(linebot) %></td>
        <td><%= link_to 'Destroy', linebot, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Linebot', new_linebot_path %>

app/views/linebots/new.html.erb
<h1>New Linebot</h1>

<%= render 'form', linebot: @linebot %>

<%= link_to 'Back', linebots_path %>

app/views/linebots/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @linebot.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @linebot.body %>
</p>

<%= link_to 'Edit', edit_linebot_path(@linebot) %> |
<%= link_to 'Back', linebots_path %>